on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Full Scan ZAP website
    env:
      TZ: Asia/Bangkok
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: 'https://artiwarahd.github.io/'
