on:
  schedule:
    # Runs every day At 01:00.
    - cron:  '10 23 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Full Scan ZAP website
    env:
      TZ: Asia/Bangkok
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: 'https://artiwarahd.github.io/'
