on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Baselne Scan ZAP website
    env:
      TZ: Asia/Bangkok
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://artiwarahd.github.io/'
