on:
  schedule:
    # Runs every day At 01:00.
    - cron: '5 23 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Baselne Scan ZAP website
    env:
      TZ: Asia/Bangkok
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          target: 'https://artiwarahd.github.io/'
